### ISSUE TITLE
Option for latest released version of Emacs?

### ISSUE THREAD

**Issue by countvajhula** [purcell/setup-emacs#20]
Hi, thanks for making this recipe!

In some of my test scripts (in particular, for running coverage) I'd like to install a reasonably safe version of Emacs and it doesn't matter what that version is. The only considerations are that it shouldn't be too old/irrelevant and that it shouldn't be too new/unstable. I wouldn't want to use `snapshot` here since that may be unstable,  and using `27.1` or some specific version also doesn't seem ideal since over time this might become increasingly stale and might warrant some maintenance to periodically update this to a more recent stable version (esp. if the package eventually drops support for this version).

Instead, it'd be nice to have a `release` or `latest` option to use here, which always points to the latest released version of Emacs.

**Comment by purcell** [comment]
I was thinking about doing this recently. Generally it's kinda better if the builds are completely reproducible over time for any given config, but `snapshot` already breaks that assumption. I have a feeling there was some potential issue with the plan — I'll have a think and see if I can remember, otherwise I'll go ahead with this.

**Comment by countvajhula** [comment]
That makes sense, too, though you're right snapshot is an exception to that already.

I guess one possible way to resolve both could be to accept a timestamp as a parameter in some way, so that if we say something like:

```
steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Install Emacs
      uses: purcell/setup-emacs@master
      with:
        date: ${{ steps.date.outputs.date }}
        version: ${{ matrix.emacs_version }}
```

... then it would pull the `release` or `snapshot` version in relation to the provided date.

The date recipe is from https://stackoverflow.com/questions/60942067/get-current-date-and-time-in-github-workflows
