### ISSUE TITLE
Example Sourcehut Builds manifest

### ISSUE THREAD

**Issue by josephmturner** [purcell/setup-emacs#41]
Thank you for `setup-emacs`!!!

We are using it to run CI for [hyperdrive.el](https://git.sr.ht/~ushin/hyperdrive.el). For the benefit of other Sourcehut users, here's an example of `setup-emacs` used in a [Sourcehut Builds](https://man.sr.ht/builds.sr.ht/) manifest (from [here](https://git.sr.ht/~ushin/hyperdrive.el/tree/master/item/.builds)):

```
image: nixos/latest
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
sources:
  - https://git.sr.ht/~ushin/hyperdrive.el
tasks:
  - setup-emacs: |
      nix profile install 'github:purcell/nix-emacs-ci#emacs-29-1'

  - initialize-sandbox: |
      cd hyperdrive.el
      ./makem/makem.sh -vvv --sandbox=.sandbox --install-deps --install-linters

  - all: |
      # We specify the rules so we can omit lint-checkdoc and
      # lint-indent, which we'll just run locally.

      # TODO: Re-enable package-lint rule when
      # <https://github.com/purcell/package-lint/issues/227> is
      # solved.
      cd hyperdrive.el
      ./makem/makem.sh -vvv --sandbox=.sandbox lint-compile lint-declare lint-regexps tests
```

Also, any feedback you offer is greatly appreciated! :)
