### ISSUE TITLE
Error `cannot write modified lock file of flake`

### ISSUE THREAD

**Issue by unindented** [purcell/setup-emacs#49]
Hi @purcell. Thank you so much for this action!

I've started getting this error today when using `purcell/setup-emacs@master`:

```
Configuring build cache and installing Emacs
  error:
         … while updating the lock file of flake 'github:purcell/nix-emacs-ci/2a9fb400307b36d76ea7288ee6221275ddbe707d?narHash=sha256-1clhQOWKqFy4ySLw3YQgfcAFkJNzR6UhfZMowKGdV3I%3D'
  
         error: cannot write modified lock file of flake 'github:purcell/nix-emacs-ci' (use '--no-write-lock-file' to ignore)
```

Do you know what could be happening?

**Comment by akirak** [comment]
This is because the lock file is not up to date, and it should be fixed with https://github.com/purcell/nix-emacs-ci/pull/292. Sorry for my oversight.

**Comment by manateelazycat** [comment]
@akirak Canyou merge patch please? My github action failed too.

Thanks for project!

**Comment by akirak** [comment]
@manateelazycat `nix-emacs-ci` is @purcell's project, and I don't have any permission on it. Really sorry for my mistake...

**Comment by manateelazycat** [comment]
@akirak My github action test.yml is 

```
      - name: Install emacs (Linux)
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
        if: matrix.os != 'windows-latest'
```

Can I change something in test.yml to make github action works? Example, change `master` to some older version?
